name: Test
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      memcached:
        image: bitnami/memcached:1.6.17
        ports:
          - 11211:11211
      memcached-with-auth:
        image: bitnami/memcached:1.6.17
        env:
          MEMCACHED_USERNAME: user
          MEMCACHED_PASSWORD: password
        ports:
          - 11212:11211
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.5.0
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test